// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.1
// source: mb-common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransferAction int32

const (
	TransferAction_TA_None      TransferAction = 0
	TransferAction_TA_PathExist TransferAction = 1
	TransferAction_TA_LoadDirs  TransferAction = 2
	TransferAction_TA_LoadFiles TransferAction = 3
	TransferAction_TA_ReadData  TransferAction = 4
	TransferAction_TA_WriteData TransferAction = 5
)

// Enum value maps for TransferAction.
var (
	TransferAction_name = map[int32]string{
		0: "TA_None",
		1: "TA_PathExist",
		2: "TA_LoadDirs",
		3: "TA_LoadFiles",
		4: "TA_ReadData",
		5: "TA_WriteData",
	}
	TransferAction_value = map[string]int32{
		"TA_None":      0,
		"TA_PathExist": 1,
		"TA_LoadDirs":  2,
		"TA_LoadFiles": 3,
		"TA_ReadData":  4,
		"TA_WriteData": 5,
	}
)

func (x TransferAction) Enum() *TransferAction {
	p := new(TransferAction)
	*p = x
	return p
}

func (x TransferAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferAction) Descriptor() protoreflect.EnumDescriptor {
	return file_mb_common_proto_enumTypes[0].Descriptor()
}

func (TransferAction) Type() protoreflect.EnumType {
	return &file_mb_common_proto_enumTypes[0]
}

func (x TransferAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferAction.Descriptor instead.
func (TransferAction) EnumDescriptor() ([]byte, []int) {
	return file_mb_common_proto_rawDescGZIP(), []int{0}
}

type TransferStatus int32

const (
	TransferStatus_TS_None    TransferStatus = 0
	TransferStatus_TS_Success TransferStatus = 1
	TransferStatus_TS_Failed  TransferStatus = 2
)

// Enum value maps for TransferStatus.
var (
	TransferStatus_name = map[int32]string{
		0: "TS_None",
		1: "TS_Success",
		2: "TS_Failed",
	}
	TransferStatus_value = map[string]int32{
		"TS_None":    0,
		"TS_Success": 1,
		"TS_Failed":  2,
	}
)

func (x TransferStatus) Enum() *TransferStatus {
	p := new(TransferStatus)
	*p = x
	return p
}

func (x TransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_mb_common_proto_enumTypes[1].Descriptor()
}

func (TransferStatus) Type() protoreflect.EnumType {
	return &file_mb_common_proto_enumTypes[1]
}

func (x TransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferStatus.Descriptor instead.
func (TransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_mb_common_proto_rawDescGZIP(), []int{1}
}

type TransferChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TcId       string         `protobuf:"bytes,1,opt,name=tc_id,json=tcId,proto3" json:"tc_id,omitempty"` // 唯一标识
	Action     TransferAction `protobuf:"varint,2,opt,name=action,proto3,enum=pb.TransferAction" json:"action,omitempty"`
	Data       []byte         `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Statue     TransferStatus `protobuf:"varint,4,opt,name=statue,proto3,enum=pb.TransferStatus" json:"statue,omitempty"`
	TargetPath string         `protobuf:"bytes,5,opt,name=target_path,json=targetPath,proto3" json:"target_path,omitempty"`
	Offset     int64          `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *TransferChunk) Reset() {
	*x = TransferChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mb_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferChunk) ProtoMessage() {}

func (x *TransferChunk) ProtoReflect() protoreflect.Message {
	mi := &file_mb_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferChunk.ProtoReflect.Descriptor instead.
func (*TransferChunk) Descriptor() ([]byte, []int) {
	return file_mb_common_proto_rawDescGZIP(), []int{0}
}

func (x *TransferChunk) GetTcId() string {
	if x != nil {
		return x.TcId
	}
	return ""
}

func (x *TransferChunk) GetAction() TransferAction {
	if x != nil {
		return x.Action
	}
	return TransferAction_TA_None
}

func (x *TransferChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TransferChunk) GetStatue() TransferStatus {
	if x != nil {
		return x.Statue
	}
	return TransferStatus_TS_None
}

func (x *TransferChunk) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *TransferChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_mb_common_proto protoreflect.FileDescriptor

var file_mb_common_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x62, 0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0xc9, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x13, 0x0a, 0x05, 0x74, 0x63, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x63, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x2a, 0x75, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x41, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x54, 0x41, 0x5f, 0x50, 0x61, 0x74, 0x68, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x41, 0x5f, 0x4c, 0x6f, 0x61, 0x64, 0x44, 0x69, 0x72,
	0x73, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x41, 0x5f, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x41, 0x5f, 0x52, 0x65, 0x61, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x10, 0x04, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x41, 0x5f, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x10, 0x05, 0x2a, 0x3c, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x54, 0x53,
	0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x54, 0x53, 0x5f, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x53, 0x5f, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x10, 0x02, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mb_common_proto_rawDescOnce sync.Once
	file_mb_common_proto_rawDescData = file_mb_common_proto_rawDesc
)

func file_mb_common_proto_rawDescGZIP() []byte {
	file_mb_common_proto_rawDescOnce.Do(func() {
		file_mb_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_mb_common_proto_rawDescData)
	})
	return file_mb_common_proto_rawDescData
}

var file_mb_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_mb_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mb_common_proto_goTypes = []interface{}{
	(TransferAction)(0),   // 0: pb.TransferAction
	(TransferStatus)(0),   // 1: pb.TransferStatus
	(*TransferChunk)(nil), // 2: pb.TransferChunk
}
var file_mb_common_proto_depIdxs = []int32{
	0, // 0: pb.TransferChunk.action:type_name -> pb.TransferAction
	1, // 1: pb.TransferChunk.statue:type_name -> pb.TransferStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mb_common_proto_init() }
func file_mb_common_proto_init() {
	if File_mb_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mb_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mb_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mb_common_proto_goTypes,
		DependencyIndexes: file_mb_common_proto_depIdxs,
		EnumInfos:         file_mb_common_proto_enumTypes,
		MessageInfos:      file_mb_common_proto_msgTypes,
	}.Build()
	File_mb_common_proto = out.File
	file_mb_common_proto_rawDesc = nil
	file_mb_common_proto_goTypes = nil
	file_mb_common_proto_depIdxs = nil
}
